### ISSUE TITLE
Cannot create consumer in wpf app

### ISSUE THREAD

**Issue by suprunka** [rabbitmq/rabbitmq-stream-dotnet-client#148] opened 2022-07-10 18:19 UTC
When I create consumer in WPF (.NET 6) I am not able to create consumer. Code stucks at creating consumer and cannot move further.
But when I use other project also .NET 6, but service Worker, then I am able to connect and create consumer and producer. 
Code  for configuration is the same in both projects.

 var lbAddressResolver = new AddressResolver(new IPEndPoint(addresses[0], 5552));
                var config = new StreamSystemConfig
                {
                    UserName = "app_positionoverviewconsumer_dev",
                    Password = "upassword",
                    VirtualHost = "mobo",
                    AddressResolver = lbAddressResolver,
                    Endpoints = new List<EndPoint> {lbAddressResolver.EndPoint },
                    ClientProvidedName="PositionEngineConsume-locr"
                };
                var system = await StreamSystem.Create(config);

                const string stream = "test2";
                await system.CreateStream(new StreamSpec(stream));

                // Create a consumer 
                var consumer = await system.CreateConsumer(
                    new ConsumerConfig
                    {
                        Reference = Guid.NewGuid().ToString(),
                        Stream = stream,
                        OffsetSpec = new OffsetTypeTimestamp(TimeSpan.FromMinutes(35).Ticks),
                        MessageHandler = async (consumer, ctx, message) =>
                        {
                            Console.WriteLine($"message: {Encoding.Default.GetString(message.Data.Contents.ToArray())} - consumed");
                            await Task.CompletedTask;
                        }
                    });
Platform: .NET 6
I am using the latest Client version: 1.0.0-rc.4
RabbitMQ:3.9.13
![image](https://user-images.githubusercontent.com/32975594/178157189-c17e8856-91bf-4fd7-aa22-e22726073e22.png)

**Comment by Gsantomaggio** [comment] 2022-07-10 18:49
does the consumer work without WPF? In a console application for example

**Comment by Gsantomaggio** [comment] 2022-07-10 18:56
it seems to be related to this issue https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/147 right?
HAve you solved [it](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/147)?

**Comment by suprunka** [comment] 2022-07-10 19:45
yes, the issue #147  has been solved.
Consumer works perfectly without WPF, I tested now in ConsoleApp.

**Comment by suprunka** [comment] 2022-07-11 09:55
Do you have update, why it doesn't work?

**Comment by lukebakken** [comment] 2022-07-15 02:11
Closing the issue for now, but I will re-open it if we get a means to reproduce what is reported.

**Closed by lukebakken** 2022-07-15 02:11 UTC
